export const pessoas = [
  {
    nome: "Cacia Rodrigues",
    image:
      "https://ik.imagekit.io/caciasrs/PI%20-%20Gen%20RH/Desenvolvedores/CaciaSRSousa.jpg?updatedAt=1738524140565",
    github: "https://github.com/CaciaRodrigues",
    linkedin: "http://www.linkedin.com/in/caciarodrigues/",
    email: "caciasrsousa@gmail.com",
    titulo: "Desenvolvedora FullStack",
    tecnologias:
      "Java, JavaScript, TypeScript, C, Python, React, Spring, Tailwind CSS, MySQL,SQLite, Git, Node.js",
    descricao:"Sou uma Desenvolvedora de Software Fullstack autodidata, que ama aprender e muito curiosa. Descobri o universo da tecnologia e comecei a estudar durante a pandemia desenvolvendo diversos projetos focados em Front End, Back End e FullStack. Me conheça melhor clicando ali em cima!",
      funfact: "Falo 3 línguas e meu hobbie favorito é costura.",
  },
  {
    nome: "Anna Vighi",
    image: "https://ik.imagekit.io/caciasrs/PI%20-%20Gen%20RH/Desenvolvedores/AnnaVighi.jpg?updatedAt=1738612522388",
    github: "https://github.com/annavighi",
    linkedin: "https://www.linkedin.com/in/anna-vighi/",
    email: "vighianna@gmail.com",
    titulo: "Desenvolvedora FullStack",
    tecnologias: "Java, Spring Boot, JavaScript, Node.js, TypeScript, React, MySQL, PostgreSQL",
    descricao: "Aluna de ADS, apaixonada por tecnologia e comunicadora por formação. Estou sempre em busca de inovação e de aprendizado.",
    funfact: "Eu coleciono discos, imãs de geladeira e idiomas.",
  },
  {
    nome: "Marcos Lopes",
    image: "https://ik.imagekit.io/caciasrs/PI%20-%20Gen%20RH/Desenvolvedores/MarcosLopes.png?updatedAt=1738590415766",
    github: "https://github.com/marcoslopesdev",
    linkedin: "https://www.linkedin.com/in/marcosaflopes/",
    email: "99marcoslopes@gmail.com",
    titulo: "Desenvolvedor Java FullStack",
    tecnologias: "Java, Spring Boot, MySQL, React, TypeScript, Node",
    descricao: "Sou apaixonado por tecnologia e por criar soluções que tornam a vida das pessoas mais fácil. No tempo livre, gosto de ler, ver filmes, estar em contato com a natureza e aproveitar momentos com quem amo.",
    funfact: "Toco saxofone e acompanho todas as corridas de Fórmula 1.",
  },
  {
    nome: "Bruno Alexandre",
    image: "https://ik.imagekit.io/caciasrs/PI%20-%20Gen%20RH/Desenvolvedores/BrunoAlexandre.jpg?updatedAt=1738590414997",
    github: "https://github.com/brunoalexb",
    linkedin: "https://www.linkedin.com/in/brunoa-barros/",
    email: "brunoale77@gmail.com",
    titulo: "Desenvolvedor FullStack",
    tecnologias: "Java, Spring Boot, JavaScript, Node.js, TypeScript, React, Python e  MySQL",
    descricao: "Desenvolvedor fullstack que atua na criação de sistemas completos, APIs seguras e soluções inovadoras. Apaixonado por tecnologia, inovação e aprendizado contínuo.",
    funfact: "Tenho formação em História.",
  },
];
